apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: cypress-test-5
  namespace: testkube
spec:
  type: cypress/project
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube.git
      branch: main
      path: test/cypress/executor-tests/cypress-11
      authType: basic
  executionRequest:
    variables:
      CYPRESS_CUSTOM_ENV:
        name: CYPRESS_CUSTOM_ENV
        value: "CYPRESS_CUSTOM_ENV_value"
        type: basic
    args:
      - "--env"
      - "NON_CYPRESS_ENV=NON_CYPRESS_ENV_value"
    executePostRunScriptBeforeScraping: false