apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: testkube-cypress-tests
 namespace: argocd
spec:
 project: default
 source:
   repoURL: https://github.com/kubeshop/testkube.git
   targetRevision: HEAD
   path: test/cypress/executor-tests/cypress-11
   plugin:
     name: "testkube-v1.0"
 destination:
   server: https://kubernetes.default.svc
   namespace: testkube